services:

  book_catalog:
    platform: linux/amd64  
    image: ${ACR_LOGIN_SERVER}/book_catalog:${VERSION}
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mirahazall:lwoutTXmwiEsemV3PjnA8meGKdXhzV4A@dpg-cr5aa3bv2p9s73afd9bg-a.oregon-postgres.render.com/part3
    depends_on:
      - inventory_management
    restart: "no"

  inventory_management:
    platform: linux/amd64  
    image: ${ACR_LOGIN_SERVER}/inventory_management:${VERSION}
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://mirahazall:lwoutTXmwiEsemV3PjnA8meGKdXhzV4A@dpg-cr5aa3bv2p9s73afd9bg-a.oregon-postgres.render.com/part3
    restart: "no"