#
# Deploys the video-streaming microservice to Kubernetes.
# 
# To deploy:
#
# export CONTAINER_REGISTRY=<your-container-registry>
# export VERSION=<the-version-to-deploy>
# envsubst < ./scripts/kubernetes/deploy.yaml | kubectl apply -f -

# kubectl create secret generic db-secret --from-literal=database-url=postgresql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: ${ACR_LOGIN_SERVER}/book_catalog:${VERSION}
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: ${ACR_LOGIN_SERVER}/inventory_management:${VERSION}
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000